name: Build Packages

on:
  workflow_dispatch:
    inputs:
      version:
        default: '4.0.0'
        description: New version number >= 4.0.0
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  github-release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@trustwallet'
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: build packages
        run: |
          git checkout -b release-v${{ github.event.inputs.version || steps.vars.outputs.tag  }}
          bun install
          bun run build:packages
          bun run test
          bun run rename ${{ github.event.inputs.version || steps.vars.outputs.tag  }}
          bun run publish
          git add .
          git commit -m "feat: Adding release files"
          git push origin release-v${{ github.event.inputs.version || steps.vars.outputs.tag  }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            New Release 🚀
          draft: false
          prerelease: true
permissions:
  actions: write
  contents: write
  deployments: write
  packages: write
