name: Build Packages

on:
  workflow_dispatch:
    inputs:
      version:
        default: '4.0.0'
        description: New version number >= 4.0.0
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate-releases:
    name: NPM Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Set up Git user information
        run: |
          git config --global user.email "support@trustwallet.com"
          git config --global user.name "Trust"
      - name: build packages
        run: |
          bun install
          bun run build:packages
          bun run test
          bun run rename ${{ github.event.inputs.version || steps.vars.outputs.tag  }}
          bun run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  actions: write
  contents: write
  deployments: write
  packages: write
